services:
  - type: web
    name: loansprint-backend
    env: go
    buildCommand: cd backend/cmd/server && go build -tags netgo -ldflags '-s -w' -o ../../../app
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release

 
