services:
  - type: web
    name: loansprint-backend
    runtime: go
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: ./app
    envVars:
      - key: PORT
        sync: false
      - key: GIN_MODE
        value: release

 
